### ISSUE TITLE
Implement new InfluxDB 0.9 HTTP API

### ISSUE THREAD

**Issue by robinroestenburg** [olauzon/capacitor#25]
The new InfluxDB 0.9 HTTP API (<https://github.com/influxdb/influxdb.org/blob/master/source/docs/v0.9/concepts/reading_and_writing_data.md>) is a bit different from the 0.8 API which is implemented by capacitor.

What are your plans for implementing the new API?

**Comment by olauzon** [comment]
Are you using 0.9 (RC) currently? When it becomes stable, one possibility would be to add the API version number in the client configuration. We would probably default to the latest stable release and provide backwards compatibility until 1.0 is released.

**Comment by robinroestenburg** [comment]
Sounds good, hopefully they will finish 0.9 soon. I am using 0.8, but am testing/playing around with the 0.9 version.

**Comment by mnuessler** [comment]
InfluxDB 0.9.0 has just been [released today](http://influxdb.com/blog/2015/06/11/InfluxDB-v0_9_0-released-with-developer-and-production-support.html).

**Comment by olauzon** [comment]
Thanks @mnuessler. Will look into changes to support v0.8.x and v0.9.x

**Comment by mnuessler** [comment]
Any update on this by any chance?

Btw, I am not really sure if it is worth the effort to support backwards compatibility for 0.8. It seems that most clients just upgrade to the 0.9 API. And there will be no bugfixes or development on InfluxDB 0.8 anymore, so everybody has to upgrade to 0.9 anyway.

**Comment by pgress** [comment]
Would be very cool, if you would support InfluxDB 0.9

**Comment by pradeepchhetri** [comment]
@mnuessler @pgress Sorry for the huge delay in adding 0.9 support. I will take this up this weekend and ensure that at least we will have some support for fundamental influxdb operations.

**Comment by arrdem** [comment]
What's the status of this? We're looking at making use of InfluxDB and if there isn't 0.9.X support elsewhere in progress this may be something I can take up.

**Comment by pgress** [comment]
@pradeepchhetri push :)

**Comment by pradeepchhetri** [comment]
@pgress I open a pull request for supporting `post-points` https://github.com/olauzon/capacitor/pull/29
Let me know if you want if we can modify to make it further simpler.

**Comment by olauzon** [comment]
@pgress merged in v0.5.0-dev. Thanks @pradeepchhetri!

**Comment by juise** [comment]
@olauzon when do you plan merge v0.5.0-dev into master and publish it on clojars?

Thanks a lot for 0.9 support, folks!

**Comment by pradeepchhetri** [comment]
@juise Currently only the `post-points` support is added. I am planning to add support for all other operations in this weekend. I hope then we can merge it with master.

**Comment by juise** [comment]
@pradeepchhetri got it! Looking forward to see the new capacitor version in master, in clojars and finally in next Riemann release!

**Comment by olauzon** [comment]
Thanks @pradeepchhetri . As soon as you're ready we can push the new version.

**Comment by royalaid** [comment]
Just curious on the status of this issue

**Comment by kfirmanty** [comment]
@royalaid Hi, I added some basic functionality to branch 0.5.0-dev and it's now possible to post points to influx 0.9 (as seen in example here https://github.com/olauzon/capacitor/blob/v0.5.0-dev/examples/basic.clj). I should probably thought about some better API but I needed fast solution. When I will find some time I will try to improve it.

**Comment by ricardoekm** [comment]
I'm also working with Influx 0.9. Is there any update on this issue?

**Comment by olauzon** [comment]
@ricardoekm v0.5.0 with support for InfluxDB 0.9.1-0.11.x should be released within the next few days. Will update this issue when ready.

**Comment by mnuessler** [comment]
InfluxDB 0.9 has been released 11 months ago, but capacitor still does not seem to support it. I have a implemented my own simple Clojure wrapper around the InfluxDB Java client and will go with that for now instead. But still looking forward to see support in capacitor in the future...

**Comment by olauzon** [comment]
Hi @mnuessler, I just released v0.6.0 with support for more recent versions of InfluxDB. If you have the opportunity, would you mind trying it and letting me know if you run into any issues?

Please note: I am not currently using InfluxDB in production, and given their relatively recent decision to move towards a purely commercial clustering model, I will not continue long term support of this client. As usual with OSS projects, contributors and maintainers are more than welcome.
