### ISSUE TITLE
Odd behavior for timestamps older than 2001-09-09T01:46:40 (1000000000000)

### ISSUE THREAD

**Issue by heltonh2r** [olauzon/capacitor#36]
If you try to insert any point whose timestamp is older than 2001-09-09T01:46:40, it will be converted to 2001-09-09T01:46:40, except for timestamp = 0 that will be correctly inserted as 1970-01-01T00:00:00.

I saw that there is a right padding logic to make ts always have a certain number of zeros. 
Would not be clearer if write-point function had an optional param for user set what kind of precision he/she wants, instead of this padding logic? 

Anyway capacitor is an excellent library, thanks for creating it.

**Comment by olauzon** [comment]
Yes, agreed. Would be much better to have precision as a parameter. I'll try to get something for that very soon. Thanks!

**Comment by fredmonroe** [comment]
I bumped into this too.
I was able to work around the issue by formatting my own timestamp strings and ensuring they are 19 characters long. Otherwise the library has been great, thank you for making it.

**Comment by olauzon** [comment]
Library is no longer maintained.
