### ISSUE TITLE
Test environment? 

### ISSUE THREAD

**Issue by jdkealy** [olauzon/capacitor#37]
Hi, 

Sorry to write an issue here as I don't see a google group, but do you have any pointers on setting up a test environment? I tried setting up a test database however, deleting and creating the database between tests was causing issues ( they seem to happen asynchronously ), now I'm just trying to figure out how to write a statement to truncate tables between tests. 

In the influx cli I can write "delete from quotes;" to truncate the quotes table, but I can't figure out how to write the equivalent via the clojure client. Any advice? Many thanks, great library.

**Comment by olauzon** [comment]
Library is no longer maintained.
